#!/usr/bin/env bash
set -e

get_theme() {
    current=$(gsettings get org.gnome.desktop.interface color-scheme)
    if [[ "$current" == "'prefer-dark'" ]]; then
        echo "dark"
    else
        echo "light"
    fi
}

if [[ "$1" == "--get" ]]; then
    get_theme
    exit
fi

if [[ "$1" == "--toggle" ]]; then
    current=$(get_theme)
    if [[ "$current" == "dark" ]]; then
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
        echo "light"
    else
        gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        echo "dark"
    fi
    exit
fi

# toggle theme
if [[ "$(get_theme)" == "dark" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    echo "light"
else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    echo "dark"
fi
