[window]
decorations = 'none'

[keyboard]
bindings = [
	    { key = "W", mods = "Control|Shift", action = "Quit"},
	    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	   ]

[general]
import = [
    "~/.config/alacritty/alacritty-auto-theme/theme.toml"
]
